### ISSUE TITLE
迁移 ParaTranz

### ISSUE THREAD

**Issue by MuXiu1997** [Kiwi233/Translation-of-GTNH#285]
# 参考

- #224

# ParaTranz 仓库

- [Translation-of-GTNH](https://paratranz.cn/projects/4964)

# 进度 - 任务书 -> ParaTranz

- [x] ParaTranz 接口反馈, 更新

- [x] 脚本代码更新: https://github.com/MuXiu1997/GTNH-translation-compare/tree/rework

- [x] 新创建 Issue Tag

- [x] 新创建 Issue 模板: #286

- [x] 新创建 Workflows: #286

# 进度 - ParaTranz -> 任务书

- [x] 新创建 Issue Tag

- [x] 新创建 Issue 模板: #289

- [x] 新创建 Workflows: #289

# 进度 - *.zs + *.lang -> ParaTranz

- [x] ZenScript 文件结构调整建议 GTNewHorizons/GT-New-Horizons-Modpack#11671

- [x] 脚本代码更新 parse pack: https://github.com/MuXiu1997/GTNH-translation-compare/tree/rework

- [x] 新创建 Issue Tag

- [x] 新创建 Issue 模板 #293

- [x] 新创建 Workflows #293

- [x] 手动上传 lang 历史词条

- [x] 翻译 zs 词条 

# 进度 - ParaTranz -> *.zs + *.lang

- [x] 新创建 Issue Tag

- [x] 新创建 Issue 模板 #293

- [x] 新创建 Workflows #293

# 进度 - gt-lang -> ParaTranz

- [x] 新创建 Issue Tag

- [x] 新创建 Issue 模板

- [x] 新创建 Workflows

# 进度 - ParaTranz -> gt-lang

- [x] 新创建 Issue Tag

- [x] 新创建 Issue 模板

- [x] 新创建 Workflows

**Comment by MuXiu1997** [comment]
[Translation-of-GTNH](https://paratranz.cn/projects/4964)
# 首次导入

Quest Book 导入版本: 2.2.0.0
Lang 导入版本: 2.2.0.0
GT Lang 导入版本: 2.2.0.0
Zs 导入版本: 2.2.3

其中 Zs 未翻译, 需要维护译文, 欢迎贡献
@iouter @Discreater @ChromicRedBrick 

@Kiwi233

**Comment by iouter** [comment]
正好可以招人测试？
@Kiwi233

**Comment by iouter** [comment]
@MuXiu1997 gt.lang 7万条是不是太多了，要不要切割一下？

**Comment by iouter** [comment]
本来以为读取太多条目会搞崩服务器，但是现在似乎没问题了？

**Comment by MuXiu1997** [comment]
和站长聊过负载的问题
目前的词条本身的比有的项目少一个数量级
只是元数据多一些
文件里存了原文和词条所在的位置信息

**Comment by iouter** [comment]
好，没问题就行

**Comment by fengluo2** [comment]
我应该如何参与ParaTranz上的翻译
